line.bot:
  channel-id: ${LINE_BOT_CHANNEL_ID}
  channel-secret: ${LINE_BOT_CHANNEL_SECRET}
  channel-token-supply-mode: supplier
  api-end-point: https://api.line.me/
  target: ${LINE_BOT_TARGET}

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: ${line.bot.channel-id}
      client-secret: ${line.bot.channel-secret}
      grant-type: client_credentials
      access-token-uri: ${line.bot.api-end-point}v2/oauth/accessToken
      client-authentication-scheme: form